name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - name: Construir con Maven
        run: mvn clean package -DskipTests

      - name: Guardar paquete generado para el trabajo de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: moviecards-java
          path: target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - name: Instalar Chrome y ChromeDriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -L -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Ejecutar la aplicación
        run: mvn spring-boot:run & sleep 60

      - name: Ejecutar pruebas
        run: mvn clean verify

  qa:
    needs: test
    runs-on: self-hosted
    continue-on-error: true

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - name: Verificar Java y Maven
        shell: cmd
        run: |
          java -version
          mvn -version
          where mvn

      - name: Construir con Maven
        shell: cmd
        run: mvn clean package -DskipTests

      - name: Ejecutar análisis SonarQube
        shell: cmd
        run: mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=admin -Dsonar.password=4daniel -Dsonar.qualitygate.wait=true

  deploy:
    needs: qa
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java

      - name: Desplegar en Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: moviecards-saigua
          slot-name: Production
          package: "*.jar"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9ECDE03922444DD38A42DF8F6B3EE2B3 }}